version: '3'

volumes:
  sqldatafiles:

networks: 
    vitrinedeveiculos-rede:
        driver: bridge

services:

  vitrinedeveiculos.mysql:
    container_name: vitrinedeveiculos.mysql
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"      
      MYSQL_DATABASE: vitrinedeveiculos    
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:     
    volumes:
      - sqldatafiles:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vitrinedeveiculos-rede

  vitrinedeveiculos.api:
    container_name: vitrinedeveiculos.api  
    image: ${DOCKER_REGISTRY-}vitrinedeveiculosapi
    build:
      context: .
      dockerfile: backend/Backend.Api/Dockerfile
    restart: always      
    ports: 
      - "5000:80"
      - "5001:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vitrinedeveiculos-rede

  vitrinedeveiculos.app:
    container_name: vitrinedeveiculos.app
    image: ${DOCKER_REGISTRY-}vitrinedeveiculosapp
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always      
    ports: 
      - "4300:90"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vitrinedeveiculos-rede