version: '2.2'

volumes:
  sqldatafiles:
  # mongodatafiles:
  
services:
  vitrinedeveiculos.mysql:
    container_name: vitrinedeveiculos.mysql
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always    
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"      
      MYSQL_DATABASE: vitrinedeveiculos    
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10  
    volumes:
      - sqldatafiles:/var/lib/mysql
#    networks:
#      - vitrinedeveiculos-rede

  # vitrinedeveiculos.mongodb:
    # container_name: vitrinedeveiculos.mongodb  
    # image: mongo
    # restart: always
    # ports:
      # - "27017:27017"
    # volumes:
      # - mongodatafiles:/data/db
#    networks:
#      - vitrinedeveiculos-rede
        
  # vitrinedeveiculos.api:
    # container_name: vitrinedeveiculos.api  
    # image: ${DOCKER_REGISTRY-}vitrinedeveiculosapi
    # build:
      # context: .
      # dockerfile: vitrinedeveiculos.Api/Dockerfile
    # restart: always      
    # ports: 
      # - "5000:80"
      # - "5001:443"
    # depends_on:
       # vitrinedeveiculos.mysql:
          # condition: 'service_healthy'
       # vitrinedeveiculos.mongodb:
          # condition: 'service_started'
    # networks:
      # - vitrinedeveiculos-rede

networks: 
    vitrinedeveiculos-rede:
        driver: host